-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le: Dim 12 Mai 2019 à 19:00
-- Version du serveur: 5.5.54-0ubuntu0.14.04.1
-- Version de PHP: 5.5.9-1ubuntu4.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `Musth`
--

-- --------------------------------------------------------

--
-- Structure de la table `courrier`
--

CREATE TABLE IF NOT EXISTS `courrier` (
  `position` int(10) NOT NULL AUTO_INCREMENT,
  `attribut` varchar(10) NOT NULL,
  `memorandum` varchar(25) NOT NULL,
  `date` date NOT NULL,
  `numcontact` varchar(255) NOT NULL,
  `objet` varchar(255) NOT NULL,
  `texte` text NOT NULL,
  PRIMARY KEY (`position`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=64 ;

--
-- Contenu de la table `courrier`
--

INSERT INTO `courrier` (`position`, `attribut`, `memorandum`, `date`, `numcontact`, `objet`, `texte`) VALUES
(10, '', '', '2015-12-17', '1', 'DÃ©simlockage de mon mobile', 'Suite Ã  votre rÃ©ponse Ã  mon courrier du 09/03/2013 sur le dÃ©simlockage de mon mobile (06 72 97 73 00). Je vous recontacte afin de finaliser mon dossier. L''appareil concernÃ© porte le numÃ©ro IMEI 01 241600 548406 2. Vous trouverez en piÃ¨ces jointes listÃ©es ci-aprÃ¨s les informations complÃ©mentaires demandÃ©es. Dans l''attente de votre rÃ©ponse et de la constatation effective du dÃ©simlockage de mon mobile, je vous prie de bien vouloir agrÃ©er l''expression de mes meilleures salutations.'),
(11, '', '', '2015-12-17', '2', 'DÃ©claration commune des revenus des professions indÃ©pendantes 2009 - 2010', 'Suite Ã  votre courrier du 1er fÃ©vrier 2013 concernant la mise Ã  jour de mon dossier et le recalcul de mes cotisations, je vous rappelle que la cessation de mon activitÃ© de nÃ©gociation immobiliÃ¨re a eu lieu le 31/07/2010.\r\nVous trouverez dans les piÃ¨ces jointes listÃ©es ci-aprÃ¨s le montant de mes revenus d''activitÃ© pour les annÃ©es 2009 et 2010. Je vous prie Ã©galement d''ajouter ces piÃ¨ces Ã  mon dossier portant la rÃ©fÃ©rence 97C186063919083.\r\n<br>\r\nSachez que je suis actuellement en phase d''Ã©tude de faisabilitÃ© sur un projet de crÃ©ation d''entreprise de services touristiques depuis le mois de janvier 2012. Je mÃ¨ne cette activitÃ© avec une grande motivation et confiance en l''avenir et cela Ã  temps plein et au quotidien.\r\n<br>\r\nEn vous remerciant de l''attention que vous porterez Ã  cette prÃ©sente lettre, je vous prie de bien vouloir agrÃ©er Monsieur, l''expression de mes meilleures salutations.\r\n'),
(16, '', '', '2015-12-17', '3', 'Demande d''envoi de fiche de paie', 'Dans le cadre de la constitution de mon dossier d''inscription Ã  la couverture maladie universelle, je suis tenu de fournir certains justificatifs utiles. Pourriez vous me faire parvenir par retour un exemplaire de fiche de paie suite Ã  la mission pour votre client B2S au mois de dÃ©cembre 2012.\r\n<br>\r\nJe poursuis ma recherche d''un emploi qui me permettra d''avoir une Ã©pargne suffisante pour lancer mon activitÃ© de voyagiste indÃ©pendant et honnorer mes charges.\r\n<br>\r\nDans l''attente de votre rÃ©ponse, je vous prie de bien vouloir agrÃ©er l''expression des mes meilleures salutations.'),
(24, '', '', '2015-12-17', '9', 'DÃ©claration de non-candidature', 'Je vous contacte afin de vous informer que j''ai fait le choix de ne pas proposer ma candidature Ã  deux des trois offres d''emploi que vous m''avez proposÃ©es lors de notre prÃ©cÃ©dent entretien. Il s''agit des offres dÃ©signÃ©es par les numÃ©ros 001QBBL et 003NTMN. AprÃ¨s rÃ©flexion je peux affirmer que ces deux offres ne correspondent pas Ã  mes aspirations. D''autre part, sachez que je cherche Ã  concrÃ©tiser votre offre d''emploi de rÃ©ceptionniste en hÃ´tellerie vie l''organisme OMNIS. Naturellement je m''engage Ã  vous tenir informÃ©s d''un prochain changement de situation. D''autre part je me tiens toujours disponible pour assister Ã  une nouvelle rÃ©union d''information sur les dispositifs d''aide Ã  la crÃ©ation d''entreprise. Pourriez-vous me proposer une date pour l''une des prochaines sessions organisÃ©es. Cela me permettra de valider certains choix et approfondir ma dÃ©couverte du dispositif N.A.C.R.E. (Nouvelles Aides Ã  la CrÃ©ation d''Entreprise). En vous remerciant de l''attention que vous porterez Ã  cette prÃ©sente lettre, je vous prie de bien vouloir agrÃ©er mes meilleures salutations.\r\n '),
(25, '', '', '2015-12-17', '9', 'Candidature au poste d''employÃ© de rayon libre service', 'Je me permet de vous contacter afin de vous proposer ma candidature au poste d''employÃ© de rayon libre service. En effet je possÃ¨de dÃ©jÃ  une expÃ©rience de la grande distribution pour avoir occuppÃ© ce type de poste pour les rayons sport-cycles-piscine et jouets au sein de l''hypermarchÃ© Cora de Dorlisheim.\r\n<br><br> Je prÃ©sente un volontarisme certain et suis rÃ©ellement attachÃ© Ã  la valeur du service rendu au client. Je postule Ã  cette offre afin de prendre le recul nÃ©cÃ©ssaire Ã  mon projet de crÃ©ation d''entreprise de services touristiques.\r\n<br><br> Sachant que j''approche d''une belle Ã©tape favorable Ã  un lancement d''activitÃ© dans les rÃ¨gles, votre offre de contrat Ã  durÃ©e dÃ©terminÃ©e de 3 mois se prÃ©sente comme un compromis idÃ©al entre le besoin de faire autre chose et conserver le cap initiÃ© par mes prÃ©cÃ©dents choix professionnels d''entrepreneur.\r\n<br><br> Nous avons la possibilitÃ© de se rencontrer pour clarifier les points essentiels et pour Ã©valuer mon profil, je vous prie de bien vouloir trouver en piÃ¨ce jointe un exemplaire de mon curriculum vitae et son introduction. Dans l''attente d''une rÃ©ponse favorable de votre part, veuillez agrÃ©er l''expression de mes meilleures salutations.'),
(26, 'none', '', '2015-12-17', '9', 'Demande d''inscription aux sessions thÃ©matiques', 'Suite Ã  ma participation Ã  la prestation du 05 avril intitulÃ©e ''Atelier Travailler en Allemagne'', j''ai pris connaissance du listing de sessions thÃ©matiques dÃ©diÃ©es aux crÃ©ateurs d''entreprise. Or ces sessions de formation organisÃ©es par l''agence PÃ´le Emploi de Strasbourg sont un atout considÃ©rable pour acquÃ©rir des savoirs faire capitaux pour lancer une activitÃ©.\r\n<br>\r\n<br>\r\nAinsi je souhaite organiser ma participation Ã  ces actions afin de complÃ©ter mes compÃ©tences. En tenant compte de la forte demande existante et dans la mesure oÃ¹ l''une ou l''autre de ces formation n''accepterait plus d''inscriptions supplÃ©mentaires, je vous transmet ci-aprÃ¨s mes trois premiers choix de formation. Pour optimiser mon temps de prÃ©sence et si cela est possible pouvez vous valider mon inscriptions pour les prochaines sessions suivantes?\r\n<br>\r\n<br>\r\n   - L''importance de l''image du chef d''entreprise -partie 1\r\n<br>\r\n   - Le WEB : un site Internet pour votre entreprise ?\r\n<br>\r\n   - E-commerce\r\n<br>\r\n<br>\r\nJe vous remercie d''avance et dans l''attente de votre rÃ©ponse et de l''atelier ''CrÃ©er son entreprise pourquoi pas ?''  organisÃ© le 24 avril 2013 au tremplin entreprises de Mutzig, je vous prie de bien vouloir accepter mes meilleures salutations. '),
(29, 'none', '', '2015-12-17', '18', 'nouveau courrier vers alsace interim', ''),
(30, 'none', '', '2015-12-17', '61', 'Attestation d''hÃ©bergement', ''),
(31, 'none', '', '2015-12-17', '72', 'PrÃ©paration Ã  notre entretien du 22 juillet 2013', 'Je me permet de vous contacter afin de vous faire part du plan de mon intervention du 22 juilet.<br>\n<br>-Moyens Humains ,techniques et financiers\n<br>-Le produits et leur dÃ©veloppement\n<br>-La production et le calendrier\n<br>-MarchÃ© et concurrence\n<br>-Marketing et ventes -commercialisation\n'),
(32, 'none', '', '2015-12-17', '36', 'Sur l''Ã©tat de nos produits et les moyens Ã  dÃ©velopper', 'Je me permet de vous contacter afin de vous faire part de l''état actuel de nos produits. En effet nous sommes en pleine rédaction des supports de recherche et de contractualisation avec nos fournisseurs.\r\n<br>\r\n<br>\r\nD''autre part nous développons les moyens suivants:\r\n<br>\r\n<br>\r\n<b>MOYENS HUMAINS</b>\r\n<br>\r\n<br>-Conventionnement de stagiaires et Programme pédagogique\r\n<br>-vers l''embauche de salariés\r\n<br>\r\n<br>\r\n<b>MOYENS TECHNIQUES</b>\r\n<br>\r\n<br>-L''assurance responsabilité civile des professionels du tourisme\r\n<br>-Locaux et matériel\r\n<br>-Moyens de production\r\n<br>-Protection juridique\r\n<br>\r\n<br>\r\n<b>MOYENS FINANCIERS</b>\r\n<br>\r\n<br>-Bilan d''ouverture\r\n<br>-Garantie financière'),
(33, 'none', '', '2015-12-17', '2', 'RÃ¨glement suite Ã  relance amiable', 'Veuillez trouver ci-joint Ã  ce prÃ©sent courrier le rÃ¨glement d''un montant de 51 euros (cinquante et un) par chÃ¨que faisant suite Ã  votre relance amiable du 8 juillet 2013. En vous souhaitant une excellente rÃ©ception, je vous prie de bien vouloir agrÃ©er mes meilleures salutations.\r\n<br>\r\n<br>\r\n<b>NÂ° SÃ©curitÃ© Sociale :</b>1 86 06 39 19 80 83 08'),
(34, 'none', '', '2015-12-17', '1', 'Remise de demande de rÃ©duction sociale tÃ©lÃ©phonique', 'Nous vous remercions pour l''envoi du formulaire de demande de rÃ©duction tÃ©lÃ©phonique. En effet Madame PERRON FranÃ§oise dont je suis le fils et retraitÃ©e de l''HÃ´pital Pasteur de Colmar depuis le mois de dÃ©cembre 2012 serait trÃ¨s heureuse de pouvoir bÃ©nÃ©ficier d''un allÃ¨gement de ses charges relatives Ã  ses consommations tÃ©lÃ©phoniques. En espÃ©rant que notre demande sera acceptÃ©e, nous vous prions de bien vouloir recevoir nos plus aimables salutations.'),
(35, 'none', '', '2015-12-17', '196', 'Remise de la fiche << Mon Parcours >> ', 'Madame,\r\n\r\nSuite à votre courrier du 23 Juillet 2013 et dans le cadre de l''élaboration de mon contrat d''engagement, je vous prie de bien vouloir trouver ci-joint la fiche << Mon Parcours >> remplie. Actuellement allocataire du RSA je me situe en phase de pré-création d''une entreprise de commercialisation de voyages à  forfaits. Ainsi je bénéficie de l''accompagnement NACRE et désire intégrer les locaux du tremplin entreprises de Mutzig pour les 3 années d''accompagnement. Je reste à votre disposition pour toute information complémentaire utile à mon contrat d''engagement. Veuillez agréer, Madame Sahraoui l''expression de mes meilleures salutations.\r\n'),
(37, '', '', '2015-12-17', '227', 'Candidature: Assistant de production Tourisme', 'C''est avec un grand plaisir que j''ai dÃ©couvert votre offre d''emploi pour le poste d''assistant de production touristique Ã  Kehl.\r\n<br><br>\r\nEn effet comme je souhaite postuler Ã  cette offre de contrat Ã  durÃ©e indÃ©terminÃ©e, je m''adresse Ã  vous pour faciliter les Ã©changes avec l''employeur. Je bÃ©nÃ©ficie d''une expÃ©rience de travail de plusieurs mois en Allemagne et notamment Ã  Kehl chez le voyagiste Touren-Service.\r\n<br><br>\r\nFort de cette aptitude depuis 2010 annÃ©e de validation de mon diplÃ´me de production touristique, je rÃ©alise un parcours singulier de crÃ©ateur d''entreprise non formalisÃ© Ã  ce jour.\r\n<br><br>\r\nAinsi je cherche Ã  renouer Ã  mon mÃ©tier, enrichi par l''expÃ©rience de l''autoentreprise. Sachez que les conditions d''embauche que vous mentionnez me conviennent. Vu ma localisation actuelle d''hÃ©bergement Ã  Obernai, je souhaite savoir si l''employeur est en mesure de me proposer un logement Ã  proximitÃ© de l''agence.\r\n<br><br>\r\nDe plus je suis disponible rapidement pour un entretien avec l''employeur pour reprendre contact et Ã©changer sur les tenants et aboutissants de l''offre d''emploi. Je vous envoie Ã©galement les documents en FranÃ§ais et en langue Allemande Ã  transmettre pour valider ma candidature. \r\n<br><br>\r\nEn vous remerciant d''avance, je vous prie de bien vouloir agrÃ©er Madame, Monsieur, l''expression de mes meilleures salutations.'),
(38, 'none', '', '2015-12-17', '227', 'Candidature au poste de chargÃ© de diffusion booking', '(ma devise etre la ou on ne m''attends pas)'),
(39, 'none', '', '2015-12-17', '227', 'Demande de devis transport de voyageurs', ''),
(40, 'none', '', '2015-12-17', '456', 'Candidature - fÃªte de la musique', 'Alors que la date de la fÃªte de la musique approche, je vous contacte afin de proposer la candidature du groupe Sac-Ã -Potes. Notre rÃ©pertoire Pop-Rock s''Ã©toffe au fil de nos rÃ©pÃ©titions Ã  Eichhoffen. En effet, deux fois par mois toute l''Ã©quipe du sac-Ã -potes se rÃ©unit avec une ponctualitÃ© exemplaire. Franck le guitariste chanteur violoniste et percussionniste nous accueille dans une salle dÃ©diÃ©e Ã  la musique. Eric le batteur qui sillone la ligne TGV Est et prends place sur son estrade et s''Ã©chauffe sur les classiques de Jonhy Hallyday. Puis Eric dit (Rickey) chausse sa guitare et son micro sous l''oeil vigilant de Rose la chanteuse et clavieriste. Patrick et moi mÃªme viennent complÃ©ter la formation Ã  l''accordÃ©eon et Ã  la guitare basse. Chacun accorde son instrument et la rÃ©pet commence...Les deux annÃ©es prÃ©cÃ©dentes nous avons eu la chance de co-animer la fÃªte de la musique Ã  Epfig'),
(41, 'none', '', '2015-12-17', '457', 'Vinyle The Moorings', 'Merci pour la rapiditÃ© de l''envoi et le soin apportÃ© au colis. Vous trouverez ci-joint Ã  ce courrier le rÃ¨glement par chÃ¨que d''un montant de 25,60 euros. La commande porte le numÃ©ro 137. \r\n<br>Je souhaite Ã  toute l''Ã©quipe des Moorings de passer une chouette mini-tournÃ©e en Italie . Ne forcez pas trop sur le rosÃ© Ã  15 %. \r\n<br>Quant Ã  moi je profiterai de votre musique depuis chez moi grÃ¢ce Ã  mon nouveau vinyle, si j''arrive Ã  bricoler ma vieille platine pour qu''elle remarche !\r\n<br>\r\n<br>\r\nAllez ciao ...'),
(42, '', '', '2015-12-17', '667', 'Dessins techniques Banc Louisiane - Sourcing Fournisseurs', 'Alors que Monsieur Allgayer Yann a rÃ©alisÃ© la totalitÃ© des dessins techniques dÃ©signÃ©s en piÃ¨ce jointe Ã  partir d''un prototype de Banc Louisiane propriÃ©tÃ© de Mr Kempf ValÃ©ry. La propriÃ©tÃ© des dessins techniques a Ã©tÃ© attribuÃ©e Ã  Mr Kempf ValÃ©ry.\r\n<br><br>\r\nPar ce projet commun, Monsieur Yann Allgayer et moi mÃªme sommes liÃ©s par une entreprise crÃ©e de fait, visant Ã  commercialiser par les moyens de la grande distribution le Banc Louisiane.\r\n<br><br>\r\nAinsi j''autorise Mr Allgayer Yann Ã  disposer des dessins techniques citÃ©s en bas de page et protÃ©gÃ©s par la propriÃ©tÃ© industrielle, dans le seul et unique but de fournir un rapport de recherche de fournisseurs capables de fabriquer les piÃ¨ces contenues dans ces dessins techniques. Le rapport de (sourcing) doit permettre la tarification pour une sÃ©rie de 100 kits de Bancs Louisiane livrÃ©s aux diffÃ©rents clients selon leurs contraintes de livraison.\r\n<br><br>\r\nDe plus le mode de livraison sur europalettes doit faciliter la prÃ©sentation du produit en magasin. L''assemblage final est rÃ©alisÃ© par le client utilisateur. Cet assemblage consiste en la mise en position de lattes en bois sur les profils d''assise et leur serrage via une sÃ©rie de boulons fournis dans le kit.'),
(44, 'none', '', '2015-12-17', '832', 'Candidature: Adjoint au responsable environnement-hygiÃ¨ne-sÃ©curitÃ© en industrie', 'Depuis janvier 2012 je me suis consacrÃ© Ã  la crÃ©ation d''une entreprise de services touristiques basÃ©e sur l''Ã©laboration d''un programme informatique sensiblement inspirÃ© par l''industrie automobile et la firme Bugatti en particulier. \r\n<br><br>\r\nOr Ã  ce jour mon projet n''a pas trouvÃ© d''issue favorable malgrÃ© la passion et l''Ã©nergie investie. Au cours de mon cursus d''entrepreneur, j''ai acquis rigueur et autonomie dans la planification de circuits touristiques Ã  forfaits. \r\n<br><br>\r\nPour tout crÃ©ateur d''entreprise, Ãªtre force de proposition surtout en matiÃ¨re d''innovation est une clÃ© de rÃ©ussite importante sinon capitale. Ainsi j''ai dÃ©veloppÃ© un concept de voyagiste en prenant le meilleur de l''industrie comme exemple. \r\n<br><br>\r\nVÃ©ritable artisan de ma carriÃ¨re professionnelle, je m''adapte aux situations de travail, et anticipe toute prise de dÃ©cision importante. Les mÃ©tiers du tourisme sont concernÃ©s particuliÃ¨rement par les problÃ©matiques environnementales et de plus en plus de tour-opÃ©rateurs se positionnent sur les thÃ©matiques d''Ã©co-tourisme et tourisme responsable.\r\n<br><br>\r\nToutefois j''Ã©prouve le dÃ©sir de renouer avec l''emploi et valoriser mon savoir faire acquis au sein d''une entreprise d''excellence comme Bugatti. Ainsi du fait de mon choix de rÃ©orienter mon avenir professionnel, je vous remet ma candidature au poste d''adjoint au responsable environnement-hygiÃ¨ne-sÃ©curitÃ©. De plus je suis intÃ©ressÃ© par l''embauche en contrat de professionnalisation.\r\n<br><br>\r\nVeuillez recevoir mes meilleures salutations.'),
(47, 'none', '', '2016-01-14', '1544', 'Candidature: Poste de Bagagiste Voiturier Anglais - Allemand', 'Suite Ã  notre bref entretien du 14 janvier 2016, je tiens Ã  vous confirmer ma disponibilitÃ© pour le poste de voiturier bagagiste. Si vous le souhaitez nous pouvons nous rencontrer Ã  nouveau. Je souhaiterais connaÃ®tre vos modalitÃ©s pour un essai comme voiturier baggagiste. Parler de la petite enquete lustrage vehicule.'),
(48, 'none', '', '2016-02-12', '2', 'RÃ¨glement Ã©chÃ©ancier', 'Je vous prie de bien vouloir recevoir en piÃ¨ces jointes les chÃ¨ques dus pour le paiement de mes cotisations sociales  du 4e trim 09 et 3e trim 10. En rÃ©fÃ©rence Ã  votre courrier du 09 fÃ©vrier 2016.'),
(49, 'none', '', '2016-02-25', '2', 'RÃ¨glement Ã©chÃ©ance 2 sur 7', 'Je vous prie de bien vouloir recevoir en piÃ¨ce jointe le chÃ¨que de 25.00 â‚¬ pour le rÃ¨glement de la deuxiÃ¨me Ã©chÃ©ance en date du 18 mars 2016. Vous trouverez Ã©galement une copie de mon Ã©chÃ©ancier afin de vous faciliter l''accÃ¨s Ã  mon dossier. En vous souhaitant une bonne rÃ©ception, veuillez agrÃ©er mes meilleures salutations.'),
(50, 'none', '', '2016-02-25', '2', 'RÃ¨glement Ã©chÃ©ance 3 sur 7', 'Je vous prie de bien vouloir recevoir en piÃ¨ce jointe le chÃ¨que de 25.00 â‚¬ pour le rÃ¨glement de la troisiÃ¨me Ã©chÃ©ance en date du 18 avril 2016. Vous trouverez Ã©galement une copie de mon Ã©chÃ©ancier afin de vous faciliter l''accÃ¨s Ã  mon dossier. En vous souhaitant une bonne rÃ©ception, veuillez agrÃ©er mes meilleures salutations.'),
(51, 'none', '', '2016-02-25', '2', 'RÃ¨glement Ã©chÃ©ance 4 sur 7', 'Je vous prie de bien vouloir recevoir en piÃ¨ce jointe le chÃ¨que de 25.00 â‚¬ pour le rÃ¨glement de la quatriÃ¨me Ã©chÃ©ance en date du 18 mai 2016. Vous trouverez Ã©galement une copie de mon Ã©chÃ©ancier afin de vous faciliter l''accÃ¨s Ã  mon dossier. En vous souhaitant une bonne rÃ©ception, veuillez agrÃ©er mes meilleures salutations.'),
(52, 'none', '', '2016-02-25', '2', 'RÃ¨glement Ã©chÃ©ance 5 sur 7', 'Je vous prie de bien vouloir recevoir en piÃ¨ce jointe le chÃ¨que de 25.00 â‚¬ pour le rÃ¨glement de la cinquiÃ¨me Ã©chÃ©ance en date du 18 juin 2016. Vous trouverez Ã©galement une copie de mon Ã©chÃ©ancier afin de vous faciliter l''accÃ¨s Ã  mon dossier. En vous souhaitant une bonne rÃ©ception, veuillez agrÃ©er mes meilleures salutations.'),
(53, 'none', '', '2016-02-25', '2', 'RÃ¨glement Ã©chÃ©ance 6 sur 7', 'Je vous prie de bien vouloir recevoir en piÃ¨ce jointe le chÃ¨que de 14.00 â‚¬ pour le rÃ¨glement de la sixiÃ¨me Ã©chÃ©ance en date du 18 juillet 2016. Vous trouverez Ã©galement une copie de mon Ã©chÃ©ancier afin de vous faciliter l''accÃ¨s Ã  mon dossier. En vous souhaitant une bonne rÃ©ception, veuillez agrÃ©er mes meilleures salutations.'),
(54, 'none', '', '2016-02-25', '2', 'RÃ¨glement Ã©chÃ©ance 7 sur 7', 'Je vous prie de bien vouloir recevoir en piÃ¨ce jointe le chÃ¨que de 40.00 â‚¬ pour le rÃ¨glement de la septiÃ¨me et derniere Ã©chÃ©ance en date du 18 aoÃ»t 2016. Vous trouverez Ã©galement une copie de mon Ã©chÃ©ancier afin de vous faciliter l''accÃ¨s Ã  mon dossier. En vous souhaitant une bonne rÃ©ception, veuillez agrÃ©er mes meilleures salutations.'),
(55, 'none', '', '2016-05-31', '1860', 'ComplÃ©ment Ã  votre commande', 'Veuillez trouver dans cette lettre les 10 LED manquantes Ã  votre commande de supports de LED 3mm. Il s''agit bien d''une erreur de ma part. En vous remerciant de votre comprÃ©hension.\r\nÃ€ bientÃ´t chez Musth.\r\n<br>\r\n<br>\r\nValÃ©ry\r\n<br>\r\n<br>\r\nIn Musth'),
(56, 'none', '1', '2017-01-21', '667', 'Conclusions de nos prÃ©cÃ©dentes scÃ©ances de prÃ©paration Ã  la reprise d''entreprise', 'Suite Ã  nos quelques rencontres liÃ©es Ã  notre initiative rÃ©cente de dÃ©marrer une Ã©tude de faisabilitÃ© de reprise d''entreprise dans le secteur industriel tournage/fraisage. Nous avons chacun confrontÃ©s nos points de vue sur les travaux Ã  produire prÃ©alablement Ã  la reprise et avons mis en Ã©vidence notre expertise individuelle et cherchons Ã  bien dÃ©finir notre complÃ©mentaritÃ© pour mener Ã  bien ce projet. ainsi nous avons commencÃ© Ã  collecter de l''information visant Ã  bÃ¢tir un plan d''affaire en coopÃ©ration avec le cÃ©dant sur les points suivants.\r\n<br>\r\n<br> \r\n<b>L''Ã©tat actuel de l''entreprise Ã  reprendre</b>\r\n<br>\r\n<br>\r\nSi l''entreprise Ã  reprendre est en dificultÃ© nous tenterons de connaÃ®tre les raisons qui ont causÃ© les difficultÃ©s de l''entreprise et Ã©valuerons nos capacitÃ©s Ã  relever un tel dÃ©fi. Il pourrait s''agir de difficultÃ©s liÃ©es Ã  un parc de machine vieillissant, une gestion de production ou financiÃ¨re dÃ©sorganisÃ©e. Un sinistre ou autre cause ayant provoquÃ© une baisse du chiffre d''affaire. Afin de se construire une image de la santÃ© de l''entreprise nous consulterons attentivement et aidÃ©s par des conseils avisÃ©s les liasses fiscales et comptables des annÃ©es prÃ©cÃ©dentes. Les emprunts en cours d''amortissement, de mÃªme que les derniers travaux de mise au normes ou de rÃ©novations effectuÃ©s nous donneront un aperÃ§u global de l''activitÃ© de l''entreprise.\r\n<br>\r\n<br>\r\n<b>Les salariÃ©s :</b>\r\n<br>\r\n<br>\r\nSi l''entreprise comporte des salariÃ©s, nous consulterons les CV et LM de chaque salariÃ© comme premier aperÃ§u des compÃ©tences disponibles dans l''entreprise. Dans un deuxiÃ¨me temps les contrats de travail de chaque salariÃ© seront analysÃ©s et mis en cohÃ©rence avec leur diplÃ´me, rÃ©munÃ©ration, objet du recrutement et toute autre information sur le recrutement. Puis nous nous tiendrons informÃ©s du planning prÃ©visionnel des salariÃ©s au sujet des vacances et congÃ©s payÃ©s en prenant connaissance des us et coutumes de l''entreprise. Quels sont les dispositifs en place pour les RTT absences et arrÃªts maladie Ã©ventuels et l''historique. Y a t''il eu ou y a il des conflits entre salariÃ©s ? \r\n<br>\r\n<br>\r\n<b>La production:</b>\r\n<br>\r\n<br>\r\nAfin de prÃ©parer l''amÃ©lioration des procÃ©dÃ©s de fabrication nous aurons besoin de la ventilation de coÃ»ts pour chaque produit. Le cÃ©dant a t''il des recommandations au sujet de l''utilisation particuliÃ¨re de ses machines ? '),
(57, 'none', '1', '2017-01-24', '667', 'Conclusions de notre entretien du 23 janvier', 'A l''issue de cette scÃ©ance de travail nous avons dÃ©terminÃ© qu''il Ã©tait nÃ©cÃ©ssaire de produire un outil de contrÃ´le statistique de la qualitÃ© des piÃ¨ces produites. Cet outil sera complÃ©tÃ© Ã  chaque sÃ©rie de production y compris courtes. Une mÃ©trique spÃ©cifique sera observÃ©e. Nous avons conclu Ã  un ciblage spÃ©cifique d''entreprise cÃ©dÃ©e qui sera le plus favorable Ã  la rÃ©ussite du projet comme indiquÃ© dans le paragraphe stratÃ©gie.\r\n<br>\r\n<br>\r\n<b>QualitÃ©</b>\r\n<br>\r\n<br>\r\nL''influence de la qualitÃ© - statistiques - optimisation de production - rebus faux rebus - 4 familles de rebus. Quels sont les opÃ©rations courantes de maintenance du parc machines Ã  faire rÃ©aliser par des prestataires, les actions de maintenance rÃ©alisables en interne. Les indications pour prÃ©venir les pannes et arrÃªts machines.\r\n<br>\r\n<br>\r\n<b>StratÃ©gie</b>\r\n<br>\r\n<br>\r\nIl se peut que le motif de cession de l''entreprise soit une diversification des activitÃ©s de l''entreprise du cÃ©dant, ainsi il pourrait rester client de nos activitÃ©s, nous l''inviterons Ã  nous exposer sa vision stratÃ©gique de croissance en tenant compte des perspectives d''Ã©volution sur le marchÃ©. Nous souhaitons rÃ©aliser un essai en immersion Ã  titre de salariÃ© afin de maÃ®triser l''ensemble de la mÃ©thode commerciale appliquÃ©e et analyser les cas de SAV ayant eu lieu. Ã€ l''issue nous aurons les capacitÃ©s de facturation usuelles pour les principaux clients. Il existe de nombreux logiciels de gestion d''entreprise pour l''industrie, la plupart nÃ©cessitent des licences. Dassault systÃ¨me produit les meilleurs logiciels de ce genre.\r\n<br>\r\n<br>\r\n<b>NÃ©gociation</b>\r\n<br>\r\n<br>\r\nNos leviers de nÃ©gociation sont de plusieurs ordres. Le marchÃ© et son Ã©volution - le parc de machine - La clientÃ¨le - Les Locaux - L''Ã©quipe salariÃ©e.\r\n'),
(58, 'none', '1', '2017-01-25', '667', 'Conclusions de scÃ©ance de travail du 24 janvier', 'A l''issue de cette session de travail nous avons dÃ©terminÃ© les orientations de travail suivantes. Ainsi nous Ã©laborerons une stratÃ©gie fonctionnelle pour rÃ©pondre Ã  ces points. Il peut s''agir d''une feuille de calcul permettant le calcul du coÃ»t unitaire en incluant la TVA collectÃ©e. Nous produirons Ã©galement un outil permettant l''organisation d''un ilÃ´t de production de 3 machines Ã  titre d''Ã©tude de cas. Un troisiÃ¨me outil sera consacrÃ© Ã  l''Ã©valuation constante de la quantitÃ© de stock disponible en temps rÃ©el.\r\n<br>\r\n<br>\r\n<b>Chiffrage</b>\r\n<br>\r\n<br>\r\nCalcul du coÃ»t unitaire produit en fonction du coÃ»t horaire machine incluant la ventilation des charges fixes\r\n<br>\r\n<br>\r\n<b>Production</b>\r\n<br>\r\n<br>\r\nOrganisation de la production selon un diagrame de Gantt Organisation des machines en ilÃ´ts - Optimisation des arrÃªts machine\r\n<br>\r\n<br>\r\n<b>Stock</b>\r\n<br>\r\n<br>\r\nGestion de l''approvisionnement en matÃ©riaux bruts et outillage machine consommables - Gestion de l''espace de stockage'),
(59, 'none', '1', '2017-01-26', '667', 'Conclusions de la session de travail du 26 janvier', '<b>Relocalisation</b>\r\n<br>\r\n<br>\r\nUne entreprise Ã  cÃ©der dont le marchÃ© imposerait une dÃ©localisation des activitÃ©s pour rÃ©tablir une compÃ©titivitÃ© coÃ»t du travail n''est pas inclue dans notre cible. En revanche nous pouvons Ã©tudier un dossier de relocalisation d''activitÃ©s en France.\r\n<br><br><br>\r\n<b>EcosystÃ¨me</b>\r\n<br>\r\n<br>\r\nLe marchÃ© de la reprise d''entreprise est en grande partie officieux car les cÃ©dants potentiels souhaitent rester discrets pour la dÃ©marche de cession. NÃ©anmoins nous pouvons identifier des offres par l''intermÃ©diaire des professionnels de la transmissions d''entreprise notamment les cabinets comptables, avocats, banques, assurances, agents immobiliers et notaires. Il seront en mesure Ã©galement de nous indiquer l''urgence de la cession. \r\n<br><br><br>\r\n<b>ClientÃ¨le</b>\r\n<br>\r\n<br>\r\nLes offres de cessions avec une clientÃ¨le diversifiÃ©e seront privilÃ©giÃ©es. Pour se faire une image de l''entreprise Ã  un instant donnÃ© nous attirons notre curiositÃ© sur les contrats commerciaux importants arrivant Ã  Ã©chÃ©ance. Nous analyserons la segmentation selon la matrice BCG en annexe pour dÃ©limiter les potentiels de dÃ©veloppement.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n'),
(60, 'none', '1', '2017-02-02', '667', 'MÃ©morandum But - RÃ©sultats - Actions', '<b>But(s):</b>\r\n<br><br>\r\nCrÃ©er un modÃ¨le de mail qui sert de compte rendu de rÃ©union.\r\n<br><br>\r\n<b>RÃ©sultats + sources:</b>\r\n<br><br>\r\nCR crÃ©e Apprentissage du fonctionnement (quoi mettre dans quelle partie ?)\r\nDÃ©couverte de la capa machine pour ValÃ©ry\r\n<br><br>\r\n<b>Actions dÃ©coulant des rÃ©sultats:</b>\r\n<br><br>\r\nEtudier le fichier Excel dÃ¨s que dispo\r\nExpliquer principe de base de la capa Ã  Val\r\nRÃ©aliser un exemple en commun (pour crÃ©er l''outi capabilitÃ©)\r\nFormaliser la demande de devis auprÃ¨s de Mme LUTT MARIANNE sur le site de la CCI en prÃ©cisant notre partenariat.\r\n<br><br>\r\n<b>Actions Ã  prÃ©voir pour la prochaine rÃ©iunion :</b>\r\n<br><br>\r\nQuelles infos prÃ©parer Ã  soumettre Ã  un banquier lors d''une premiÃ¨re entrevue\r\n(obj : pistes de financement / pistes pour trouver une entreprise Ã  cÃ©der)\r\nEVENTUELLEMENT : Si infos bouclÃ©es : contact/prise de RDV ensemble\r\nSi temps : petit test capacitÃ© machine'),
(61, 'none', '1', '2017-03-20', '1', 'Fin de la formation des 5 jours pour entreprendre', 'projet de rÃ©aiser Ã©tude de marchÃ© sur 700 Ã©tudiants de strasbourg. Utiliser le modÃ¨le AARRR pour aller le plus loin possible vers la rÃ©servation en mode Ã©tude de marchÃ©. Ainsi il faudra avoir prÃ©parÃ© la landing page la video et le programme et connaitre les formalitÃ©s Ã  accomplir et rÃ©diger le descriptif long. les conditions de ventes seront prÃ© rÃ©digÃ©es'),
(62, 'none', '1', '2017-04-19', '1', 'Envisager une campagne publicitaire sur produits phytosanitaires - huiles essentielles - nanotechnologies', 'texte1\r\n\r\n\r\n\r\ntexte 2'),
(63, 'none', '', '2017-05-14', '2299', 'Contrat de travail HÃ´tel le Gouverneur', 'Par la prÃ©sente je vous transmet le contrat de travail actuellement en vigueur pour l''hÃ´tel le Gouverneur Ã  Obernai. Ce contrat de travail va Ãªtre modifiÃ© cette semaine car dorÃ©navent je prendrais les gardes en semaine et non le week end comme prÃ©vu et cela pour une durÃ©e minimum d''un mois. En vous souhaitant bonne rÃ©ception.\r\nVeuillez agrÃ©er mes meilleures salutations.');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
