-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le: Dim 12 Mai 2019 à 19:01
-- Version du serveur: 5.5.54-0ubuntu0.14.04.1
-- Version de PHP: 5.5.9-1ubuntu4.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `Musth`
--

-- --------------------------------------------------------

--
-- Structure de la table `motivations`
--

CREATE TABLE IF NOT EXISTS `motivations` (
  `position` int(10) NOT NULL AUTO_INCREMENT,
  `titre` varchar(255) NOT NULL,
  `texte` text NOT NULL,
  `trame` varchar(25) NOT NULL,
  PRIMARY KEY (`position`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=18 ;

--
-- Contenu de la table `motivations`
--

INSERT INTO `motivations` (`position`, `titre`, `texte`, `trame`) VALUES
(1, 'WEBCD', 'Madame, Monsieur,\r\n\r\nDepuis janvier 2012 je me suis consacré à la création d''un concept de tour opérateur. Par l''apprentissage en autodidacte, j''ai conçu et développé un programme informatique qui permet la conception de circuits touristiques sur mesure.  \r\n\r\nOr à ce jour mon projet n''a pas trouvé d''issue favorable malgré la passion et l''énergie investie. Au cours de mon cursus d''entrepreneur, j''ai acquis rigueur et autonomie dans la programmation informatique en php et mysql.\r\n\r\nDe plus j''ai appris à administrer mes différents interfaces web via le serveur Gandi. En effet au mois de juin 2014 j''ai lancé mes premiers sites dont celui ma marque de voyage. Cependant ces sites sont à ce jour hors ligne.\r\n\r\nTitulaire d''un BTS en vente et productions touristiques. J''ai acquis au cours de cette formation de deux ans un savoir faire ainsi qu''un savoir être en accueil clientèle que je souhaite mettre à profit de votre équipe.\r\n\r\nJ''ai par ailleurs été amené à travailler plusieurs mois pour le tour Opérateur "Touren service Schweda" en Allemagne en tant qu''assistant de production touristique. J''ai participé aux tâches planifiées quotidiennes tout en assurant l''accueil commercial en langue allemande et anglaise. \r\n\r\nPassionné d''aviation je souhaite reprendre les vols en instruction afin d''obtenir le second degré de pilote d''avion léger. Egalement musicien je pratique la guitare et le piano comme un bon passe-temps.\r\n\r\nVeuillez recevoir mes meilleures salutations.\r\n', ''),
(3, 'Votre candidature accueil hôtel 4 * et spa Strasbourg', 'Bonjour,\r\n\r\n \r\n\r\nAprès un point fait avec l’hôtel concernant son cahier des charges, ce dernier a pris la décision de ne pas retenir votre candidature, en effet l’hôtel recherche actuellement des profils plus expérimentés dans le domaine hôtelier, avec à minima une expérience significative en réception.\r\n\r\nNous vous souhaitons un bon courage, et une bonne continuation dans vos recherches.\r\n\r\n \r\n\r\n \r\n\r\nBien cordialement\r\n\r\nLe Service Recrutement\r\n\r\n \r\n\r\nPour toutes vos demandes recrutement: wace.rhrecrut@gmail.com\r\n\r\n\r\nCe message et toutes les pièces jointes sont confidentiels et couverts par le secret professionnel et transmis à l''intention exclusive des destinataires. Toute modification, édition, utilisation ou diffusion non autorisée est interdite. Si vous avez reçu ce message par erreur, merci de nous en avertir immédiatement soit en répondant à ce courrier, soit en adressant un mail à wace.comptabilite@gmail.com. Notre société décline toute responsabilité au titre de ce message s''il a été altéré, déformé, falsifié ou encore édité ou diffusé sans autorisation.', '1'),
(4, 'Le bouclier d''or hôtel and spa ****', 'Madame, Monsieur,\r\n\r\n \r\n\r\nNous avons bien reçu votre candidature au poste de réceptionniste au Bouclier d''Or et vous en remercions.\r\n\r\n \r\n\r\nNous sommes au regret de vous faire savoir que votre profil ne correspond pas pleinement au poste à pouvoir, mais que néanmoins nous conservons votre dossier. Nous ne manquerons pas de vous recontacter si la situation devait évoluer.\r\n\r\n \r\n\r\nNous vous remercions de l’intérêt que vous portez à notre hôtel et vous souhaitons pleine réussite dans votre recherche d’emploi.\r\n\r\n \r\n\r\nVeuillez agréer, Madame, Monsieur, l’expression de nos salutations distinguées.\r\n\r\n \r\n\r\nUte Kamlah\r\n\r\nAssistante de Direction', '1'),
(5, 'lidl', 'Bonjour,\r\n\r\nC''est avec grand intérêt que nous avons pris connaissance de votre\r\ncandidature\r\nau sein de notre société.\r\n\r\nAprès une étude très attentive de votre dossier, nous sommes au regret de\r\nne\r\npas pouvoir lui réserver une suite favorable, malgré tout l''intérêt qu''il\r\nprésente.\r\n\r\nNous vous souhaitons d''aboutir dans vos recherches et sommes convaincus que\r\n\r\nvous trouverez un emploi en adéquation avec vos aspirations\r\nprofessionnelles.\r\n\r\nVous remerciant de l''intérêt que vous avez porté à notre société, nous vous\r\n\r\nprions d''agréer nos salutations distinguées.', '1'),
(6, 'LM Réceptionniste Novembre 2014', 'Madame Milhau,\r\n\r\nAlors que je souhaite différer mon projet de création d''entreprise de services touristiques, je cherche une expérience significative en tant que réceptionniste. \r\n\r\nJe viens d''achever une AFPR (Action de Formation Préalable au Recrutement) au sein de l''hôtel Kyriad Strabourg Palais des Congrès*** ou j''ai perfectionné mon sens du service et connaissances du logiciel Opéra. J''ai également réalisé une EMTPR (Evaluation en milieu de travail préalable au recrutement) au mois d''Août 2014 à l''hôtel Ibis de Lingolsheim sur une période de 40h.\r\n\r\nJe suis trilingue Anglais, Allemand avec un bon niveau et d''un tempérament calme et afable adapté à l''accueil clientèle.\r\n\r\nDans l''attente de votre réponse que je souhaite favorable, je vous prie Madame Milhau, de bien vouloir agréer mes meilleures salutations.', ''),
(8, 'BUGATTI AUTOMOBILES', 'Madame Moritz,\r\n\r\nDepuis janvier 2012 je me suis consacré à la création d''une entreprise de services touristiques basée sur l''élaboration d''un programme informatique sensiblement inspiré par l''industrie automobile et la firme Bugatti en particulier. \r\n\r\nOr à ce jour mon projet n''a pas trouvé d''issue favorable malgré la passion et l''énergie investie. Au cours de mon cursus d''entrepreneur, j''ai acquis rigueur et autonomie dans la planification de circuits touristiques à forfaits. \r\n\r\nPour tout créateur d''entreprise, être force de proposition surtout en matière d''innovation est une clé de réussite importante sinon capitale. Ainsi j''ai développé un concept de voyagiste en prenant le meilleur de l''industrie comme exemple. \r\n\r\nVéritable artisan de ma carrière professionnelle, je m''adapte aux situations de travail, et anticipe toute prise de décision importante. Les métiers du tourisme sont concernés particulièrement par les problématiques environnementales et de plus en plus de tour-opérateurs se positionnent sur les thématiques d''éco-tourisme et tourisme responsable.\r\n\r\nToutefois j''éprouve le désir de renouer avec l''emploi et valoriser mon savoir faire acquis au sein d''une entreprise d''excellence comme Bugatti. Ainsi du fait de mon choix de réorienter mon avenir professionnel, je vous remet ma candidature au poste d''adjoint au responsable environnement-hygiène-sécurité. De plus je suis intéressé par l''embauche en contrat de professionnalisation.\r\n\r\nVeuillez recevoir mes meilleures salutations.\r\n\r\n\r\n', ''),
(10, 'Candidature au poste de conducteur de train', 'Monsieur Brill,\r\n\r\nDepuis janvier 2012 je me suis consacré à la création d''un concept de tour opérateur. Par l''apprentissage en autodidacte, j''ai conçu et développé un programme informatique qui permet la conception de circuits touristiques sur mesure et leur commercialisation sur un interface utilisateur web.  \r\n\r\nOr à ce jour mon projet n''a pas trouvé d''issue favorable malgré la passion et l''énergie investie. Au cours de mon cursus d''entrepreneur, j''ai acquis rigueur et autonomie dans la programmation informatique.\r\n\r\nActuellement je continue à mettre à profit mes compétences en Mécanique acquises via ma formation de Baccalauréat STI Génie Mécanique en mettant en oeuvre quelques projets de fabrication, notamment de pièces en fer forgé. Sur ce chemin, je cherche à commercialiser du mobilier de jardin et des pièces imprimées en 3D.\r\n\r\nJ''ai par ailleurs été amené à travailler plusieurs mois pour le tour Opérateur "Touren service Schweda" en Allemagne en tant qu''assistant de production touristique. J''ai intégré l''équipe et participé aux tâches planifiées quotidiennes tout en assurant l''accueil commercial en langue allemande et anglaise. \r\n\r\nPassionné d''aviation je souhaite reprendre les vols en instruction afin d''obtenir le second degré de pilote d''avion léger. La formation pour accéder à cette licence m''a apporté d''excellentes notions en mécanique de Vol, Météorologie, ainsi que les connaissances de base de la règlementation de la circulation aérienne et les techniques de navigation.\r\n\r\nÉgalement musicien je pratique guitare, basse, trompette et le piano comme un bon passe-temps.\r\n\r\nVeuillez recevoir Monsieur, mes meilleures salutations.\r\n', ''),
(11, 'Candidature Chargé(e) de production informatique H/F', 'Madame Buchheit,\r\n\r\nDepuis janvier 2012 je me suis consacré à la création d''un concept de tour opérateur. Par l''apprentissage en autodidacte, j''ai conçu et développé un programme informatique qui permet la conception de circuits touristiques sur mesure. \r\n\r\nOr à ce jour mon projet n''a pas trouvé d''issue favorable malgré la passion et l''énergie investie. Au cours de mon cursus d''entrepreneur, j''ai acquis rigueur et autonomie dans la programmation informatique en php et mysql.\r\n\r\nDe plus j''ai appris à administrer mes différents interfaces web via le serveur Gandi. En effet au mois de juin 2014 j''ai lancé mes premiers sites dont celui ma marque de voyage.\r\n\r\nTitulaire d''un BTS en vente et productions touristiques. J''ai acquis au cours de cette formation de deux ans un savoir faire ainsi qu''un savoir être en accueil clientèle que je souhaite mettre à profit.\r\n\r\nJ''ai par ailleurs été amené à travailler plusieurs mois pour le tour Opérateur "Touren service Schweda" en Allemagne en tant qu''assistant de production touristique. J''ai participé aux tâches planifiées quotidiennes tout en assurant l''accueil commercial en langue allemande et anglaise.\r\n\r\nPassionné d''aviation je souhaite reprendre les vols en instruction afin d''obtenir le second degré de pilote d''avion léger. Egalement musicien je pratique la guitare et le piano comme un bon passe-temps.\r\n\r\nVeuillez recevoir mes meilleures salutations.\r\n', ''),
(12, 'Agent de planification h/f', 'Monsieur Antoni,\r\n\r\nJe vous adresse cet email afin de vous transmettre mon CV concernant l''offre d''emploi de votre agence.\r\n\r\nJe pense avoir les qualités requises pour pouvoir mener à bien cette mission, car je suis devenu quelqu''un de très organisé en essayant de monter une entreprise.\r\n\r\nAujourd''hui le temps est venu de me consacrer à un emploi dans lequel les responsabilités sont synonymes de valeur ajoutée.\r\n\r\nCet emploi me permettra d''avoir accès à l''indépendance que je continue à chercher même après l''échec du projet d''entreprise.\r\n\r\nAinsi veuillez trouver en pièce jointe mon CV de technicien planning.', ''),
(13, 'Candidature Employé(e) Polyvalent(e) petit-déjeuner', 'Bonjour,\r\n\r\nSuite à un échec dans la création de mon entreprise de services touristiques, je cherche à renouer avec l''emploi afin de gagner une meilleure assurance et confiance en moi même.\r\n\r\nPour cela je candidate activement sur les postes de réceptionniste en hôtellerie depuis le mois de Juin 2014. Mes recherches m''ont amenés à ce jour à réaliser une EMTPR (Dispositif pôle emploi permettant au chercheur d''emploi de valider son choix d''orientation professionnelle) pour l''hôtel Ibis de Lingolsheim sur une période de 40h.\r\n\r\nJe suis trilingue Anglais, Allemand avec un bon niveau et d''un tempérament calme et afable adapté à l''accueil clientèle. Facilitateur e travail en équipe je sais communiquer efficacement.\r\n\r\nAinsi je vous prie de bien vouloir accepter ma candidature au poste d''employer polyvalent dans votre établissement.\r\n \r\nCordialement. ', ''),
(14, 'Candidature Planificateur de production bilingue (F/H) en CDI', 'Monsieur Delorme,\r\n\r\nJe vous adresse cet email afin de vous transmettre mon CV concernant l''offre d''emploi de votre agence.\r\n\r\nJe pense avoir les qualités requises pour pouvoir mener à bien cette mission, car je suis devenu quelqu''un de très organisé en essayant de monter une entreprise.\r\n\r\nAujourd''hui le temps est venu de me consacrer à un emploi dans lequel les responsabilités sont synonymes de valeur ajoutée.\r\n\r\nCet emploi me permettra d''avoir accès à l''indépendance que je continue à chercher même après l''échec du projet d''entreprise.\r\n\r\nAinsi veuillez trouver en pièce jointe mon CV de technicien planning.\r\n', ''),
(15, 'REDACTEUR TECHNIQUE H/F', 'Madame Fertoul,\r\n\r\nDepuis janvier 2012 je me suis consacré à la création d''un concept de tour opérateur. Par l''apprentissage en autodidacte, j''ai conçu et développé un programme informatique qui permet la conception de circuits touristiques sur mesure.  \r\n\r\nOr à ce jour mon projet n''a pas trouvé d''issue favorable malgré la passion et l''énergie investie. Au cours de mon cursus d''entrepreneur, j''ai acquis rigueur et autonomie dans la programmation informatique en php et mysql.\r\n\r\nAinsi je m''estimme capable de mener à bien la mission proposée car j''ai acquis de bonnes capacités rédactionnelles. Je sais communiquer efficacement des concepts et des idées. Habile de mes mains également je suis quelqu''un qui s''intéresse au domaine technique dans la vie courante. \r\n\r\nA l''aise avec solidworks j''ai recemment entammé un projet personnel de banc de jardin en fer forgé entièrement dessiné avec ce logiciel.\r\n\r\n', ''),
(16, 'SOGEHO', '', ''),
(17, 'Assistant commercial et administratif', 'Madame Monsieur,\r\n\r\nDepuis janvier 2012 je me suis consacré à la création d''un concept de tour opérateur. Par l''apprentissage en autodidacte, j''ai conçu et développé un programme informatique qui permet la conception de circuits touristiques sur mesure.  \r\n\r\nOr à ce jour mon projet n''a pas trouvé d''issue favorable malgré la passion et l''énergie investie. Au cours de mon cursus d''entrepreneur, j''ai acquis rigueur et autonomie et une vraie expertise dans la programmation informatique en php et mysql.\r\n\r\nAinsi je m''estimme capable de mener à bien la mission proposée car j''ai acquis d''excellentes capacités rédactionnelles. Je sais communiquer efficacement des concepts et des idées. \r\n\r\nJ''assure l''accueil commercial de votre clientèle en trois langues notamment Anglais et Allemand. Ainsi je cherche un employeur qui me donnera la chance de faire mes preuves dans son établissement', '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
